spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:su-log-db
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
