### 테스트 요청
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "pr@gmail.com",
  "password" : "1234"
}

### 인증페이지 요청
GET http://localhost:8080/test
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0._wu9iDTpOh-L7_QbMkKmtbx9lYVFVNlgUF2IKU9FlGc